Models/MoviesModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Collection.Portal.Models
{
    public class MoviesModel
    {
        public string Title { get; set; }

        public string TranslatedTitle { get; set; }

        public DateTime? ReleaseDate { get; set; }

        public int? RunningTime { get; set; }

        public string Certification { get; set; }

        public IEnumerable<string> Formats { get; set; }

        public string Series { get; set; }

        public int? SeriesNumber { get; set; }

        public bool Watched { get; set; }

        public int? Rating { get; set; }

        public string PosterUrl { get; set; }

        public List<string> Directors { get; set; }

        public List<string> Producers { get; set; }

        public List<string> Writers{ get; set; }

        public List<string> Cast { get; set; }

        public List<string> Genres { get; set; }
    }
}

ViewModels/MovieViewModel.cs
using Collection.Portal.Extensions;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Collection.Portal.ViewModels
{
    public class MovieViewModel
    {
        [Required]
        public string Title { get; set; }

        public string TranslatedTitle { get; set; }

        public string Directors { get; set; }

        public string Producers { get; set; }

        public string Writers { get; set; }

        public string Cast { get; set; }

        public string Genres { get; set; }

        public DateTime? ReleaseDate { get; set; }

        public int? RunningTime { get; set; }

        public string Certification { get; set; }

        public IEnumerable<string> Formats { get; set; }

        public string Series { get; set; }

        public int? SeriesNumber { get; set; }

        public bool Watched { get; set; }

        public int? Rating { get; set; }

        public string PosterUrl { get; set; }
    }
}

Controllers/Web/AppController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Collection.Portal.Controllers.Web
{
    public class AppController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }
    }
}

Controllers/Web/CollectionController.cs
using Collection.Portal.Infrastructure;
using Collection.Portal.Models;
using Collection.Portal.Services.Interfaces;
using Collection.Portal.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Collection.Portal.Controllers.Web
{
    public class CollectionController : Controller
    {
        private readonly ICollectionService collectionService;

        public CollectionController(ICollectionService collectionService)
        {
            this.collectionService = collectionService;
        }

        public IActionResult Movies()
        {
            var movies = this.collectionService.Get<MoviesModel>();

            var moviesList = movies.ToList();

            ViewData["Movies"] = moviesList;

            return View();
        }

        [HttpPost]
        public IActionResult Movies(MovieViewModel model)
        {
            var modelList = new List<MovieViewModel>
            {
                model
            };

            var result = this.collectionService.PostAsync(modelList);
            return View();
        }

        public IActionResult Books()
        {
            return View();
        }

        public IActionResult Games()
        {
            return View();
        }

        public IActionResult Albums()
        {
            return View();
        }
    }
}

Views/App/About.cshtml
@{
    ViewBag.Title = "About";
}

<!DOCTYPE html>
<html>

<body>

    <h2>About</h2>

</body>
</html>

Views/App/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<!DOCTYPE html>
<html>

<body>

    <h2>Home</h2>

</body>
</html>

Views/Collection/Albums.cshtml
@{
    ViewBag.Title = "Album Collection";
}

<!DOCTYPE html>
<html>

<body>

    <h2>Album Collection</h2>

</body>
</html>

Views/Collection/Books.cshtml
@{
    ViewBag.Title = "Book Collection";
}

<!DOCTYPE html>
<html>

<body>

    <h2>Book Collection</h2>

</body>
</html>

Views/Collection/Games.cshtml
@{
    ViewBag.Title = "Game Collection";
}

<!DOCTYPE html>
<html>

<body>

    <h2>Game Collection</h2>

</body>
</html>

Views/Collection/Movies.cshtml
@model Collection.Portal.ViewModels.MovieViewModel

@{
    ViewBag.Title = "Movie Collection";
}

<!DOCTYPE html>
<html>

<body>

    @section scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    }

    <h2>Movie Collection</h2>

    <div class="container-fluid">
        <form class="form-inline">
            <div class="form-group row">
                <button id="btnCreate" type="button" class="btn btn-outline-primary ml-3" data-toggle="modal" data-target="#createForm">Create</button>

                <label class="sr-only" for="txtSearch">Search</label>
                <input type="text" class="form-control mb-2 mr-1 mb-sm-0 ml-5" id="txtSearch" placeholder="Search..." />

                <button id="btnSubmit" type="button" class="btn btn-primary">Search</button>
            </div>
        </form>
    </div>

    <div class="card-columns">
        @foreach (var movie in (List<Collection.Portal.Models.MoviesModel>)ViewData["Movies"])
        {
            <div class="card">
                <img class="card-img-top" src="@movie.PosterUrl" atl="@movie.Title" />
                <div class="card-block">
                    <h4 class="card-title">@movie.Title</h4>
                    <p class="card-subtitle">@movie.TranslatedTitle</p>
                </div>
            </div>
        }
    </div>

    <!-- Modal form for creating new movie records in the collection -->
    <div id="createForm" class="modal fade" role="dialog">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">&times;</span>
                        <span class="sr-only">Close</span>
                    </button>
                    <h4 class="modal-title" id="lblTitle">Add Movie to Collection</h4>
                </div>

                <div class="modal-body">
                    <div class="container-fluid">
                        <form method="post" action="/Collection/Movies">
                            <div class="form-group row">
                                <div class="col-sm-4">
                                    <label class="sr-only" asp-for="Title"></label>
                                    <input type="text" class="form-control" id="txtTitle" asp-for="Title" placeholder="Title:" />
                                </div>
                                <div class="col-sm-4">
                                    <label class="sr-only" asp-for="TranslatedTitle"></label>
                                    <input type="text" class="form-control" id="txtTranslatedTitle" asp-for="TranslatedTitle" placeholder="Translated Title:" />
                                </div>
                                <label class="sr-only" asp-for="ReleaseDate"></label>
                                <div class="col-sm-4">
                                    <input type="date" class="form-control" id="dtReleaseDate" asp-for="ReleaseDate" placeholder="Release Date:" />
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-sm-4">
                                    <label class="sr-only" asp-for="Directors"></label>
                                    <textarea class="form-control" rows="3" placeholder="Directors: (one per line)" asp-for="Directors" id="txtDirectors"></textarea>

                                    <label class="sr-only" asp-for="Cast"></label>
                                    <textarea class="form-control mt-2" rows="7" placeholder="Cast: (one per line)" asp-for="Cast" id="txtCast"></textarea>
                                </div>
                                <div class="col-sm-3">
                                    <label class="sr-only" asp-for="Genres"></label>
                                    <textarea class="form-control" rows="3" placeholder="Genres: (one per line)" asp-for="Genres" id="txtGenres"></textarea>

                                    <label class="sr-only" asp-for="Writers"></label>
                                    <textarea class="form-control mt-2" rows="3" placeholder="Writers: (one per line)" asp-for="Writers" id="txtWriters"></textarea>

                                    <label class="sr-only" asp-for="Producers"></label>
                                    <textarea class="form-control mt-2" rows="3" placeholder="Producers: (one per line)" asp-for="Producers" id="txtProducers"></textarea>
                                </div>
                                <div class="col-sm-5">
                                    <label class="sr-only" asp-for="RunningTime"></label>
                                    <input type="number" class="form-control" id="txtRunningTime" asp-for="RunningTime" placeholder="Running Time: (mins)" />

                                    <label class="sr-only" asp-for="Certification">Certification:</label>
                                    <select class="form-control mt-2" asp-for="Certification" id="sltCertification">
                                        <option disabled selected>Certification:</option>
                                        <option value="U">U</option>
                                        <option value="PG">PG</option>
                                        <option value="12A">12A</option>
                                        <option value="12">12</option>
                                        <option value="15">15</option>
                                        <option value="18">18</option>
                                    </select>

                                    <label class="sr-only" asp-for="Formats">Formats:</label>
                                    <select multiple class="form-control" asp-for="Formats" id="sltFormats">
                                        <option value="Blu-Ray">Blu-Ray</option>
                                        <option value="DVD">DVD</option>
                                        <option value="Digital">Digital</option>
                                        <option value="VHS">VHS</option>
                                    </select>

                                    <div class="row">
                                        <label class="ml-3">Is this part of a series?</label>
                                        <div class="col-sm-6">
                                            <label class="sr-only" asp-for="Series"></label>
                                            <input type="text" class="form-control" asp-for="Series" id="txtSeries" placeholder="Series:" />
                                        </div>
                                        <div class="col-sm-6">
                                            <label class="sr-only" asp-for="SeriesNumber"></label>
                                            <input type="number" class="form-control" asp-for="SeriesNumber" id="txtSeriesNumber" placeholder="No.:" />
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-sm-2">
                                    <div class="form-check mt-2">
                                        <label class="form-check-label" asp-for="Watched">
                                            <input class="form-check-input" type="checkbox" name="chkWatched" asp-for="Watched" id="chkWatched" /> Watched?
                                        </label>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <label class="sr-only" asp-for="Rating"></label>
                                    <select class="form-control" asp-for="Rating" id="sltRating">
                                        <option disabled selected>Rating:</option>
                                        <option value="0">☆☆☆☆☆</option>
                                        <option value="1">★☆☆☆☆</option>
                                        <option value="2">★★☆☆☆</option>
                                        <option value="3">★★★☆☆</option>
                                        <option value="4">★★★★☆</option>
                                        <option value="5">★★★★★</option>
                                    </select>
                                </div>
                                <div class="col-sm-7">
                                    <label class="sr-only" asp-for="PosterUrl"></label>
                                    <input type="url" class="form-control" asp-for="PosterUrl" id="txtPosterUrl" placeholder="Poster URL:" />
                                </div>

                            </div>
                            <button type="submit" class="btn btn-outline-info">Submit</button>
                        </form>
                    </div>
                </div>

                <div class="modal-footer">
                </div>

            </div>
        </div>
    </div>

</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/sites.css" />

</head>

<body>

    <header>
        <div>
            <div>
                <div class="nav-logo">

                </div>
                <div class="nav-column">
                    <nav>
                        <ul class="nav-list">
                            <li><a asp-controller="App" asp-action="Index">Home</a></li>
                            <li class="nav-dropdown">
                                <a href="javascript:void(0)" class="drop-btn">Collection</a>
                                <div class="drop-items">
                                    <a asp-controller="Collection" asp-action="Movies">Movies</a>
                                    <a asp-controller="Collection" asp-action="Books">Books</a>
                                    <a asp-controller="Collection" asp-action="Games">Games</a>
                                    <a asp-controller="Collection" asp-action="Albums">Albums</a>
                                </div>
                            </li>
                            <li><a asp-controller="App" asp-action="About">About</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </header>

    <div class="body-content">
        @RenderBody()
        <hr />
    </div>

    <footer>

    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @RenderSection("scripts", false)

    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>

</body>
</html>